server:
  port: 9324

spring:

  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/postgres?user=${DATABASE_USER}&password=${DATABASE_PASSWORD}

  application:
    name: newroutes

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: newroutes
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
    open-in-view: true

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

  config:
    import: optional:file:.env[.properties]

security:
  jwt:
    header: "Bearer "
    claim: "roles"
    secret: ${JWT_SECRET}
    access-token:
      header: "access_token"
      expiration-hours: 1
    refresh-token:
      header: "refresh_token"
      expiration-days: 30
    error:
      header: "error"

integrations:
  sendinblue:
    baseurl: "https://api.sendinblue.com/v3"
    password: ${SENDINBLUE_PASSWORD}
    apikey: ${SENDINBLUE_APIKEY}
  cloudmersive:
    baseurl: "https://api.cloudmersive.com"
    apikey: ${CLOUDMERSIVE_APIKEY}
  true_way:
    baseurl: "https://trueway-geocoding.p.rapidapi.com"
    apikey: ${TRUEWAY_APIKEY}
