server:
  port: 9324

spring:

  datasource:
    url: jdbc:postgresql://db.ygvgkodxudmsqnnpmmbh.supabase.co:5432/postgres?user=postgres&password=KPChLaC2S93QowoT

  application:
    name: newroutes

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: newroutes
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
    open-in-view: true

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

  config:
    import: optional:secrets.properties

security:
  jwt:
    header: "Bearer "
    claim: "roles"
    secret: "bFiG3UI6Kx5I0kPTEC4GOEjDd2bKAUSJXsQTItQtfEcKxbBANrGQMCMi0KeV2A65e3dwMl0uryvYn62J7Fjyvk08sFVSqJchO6m"
    access-token:
      header: "access_token"
      expiration-hours: 1
    refresh-token:
      header: "refresh_token"
      expiration-days: 30
    error:
      header: "error"

integrations:
  sendinblue:
    baseurl: "https://api.sendinblue.com/v3"
    password: "SPNT2Q9ZcrRvmAqK"
    apikey: "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"
  cloudmersive:
    baseurl: "https://api.cloudmersive.com"
    apikey: "389a09ae-1303-4263-b5b1-5a7d08823e98"
  true_way:
    baseurl: "https://trueway-geocoding.p.rapidapi.com"
    apikey: "673c0c2657msh496ba5000ebbe42p1a944cjsnd0fa69e71bb2"
