#Workflow name
name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the branch master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Maven settings file
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: '[
                      {
                        "id": "github",
                        "configuration": {
                          "httpHeaders": {
                            "property": {
                              "name": "Authorization",
                              "value": "Bearer ${{ secrets.ACCESS_TOKEN }}"
                            }
                          }
                        }
                      }
                    ]'

      - name: Run Pipeline
        run: mvn deploy -DskipTests


      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: SebastianoFazzino/newroutes
          retain_days: 30
          keep_minimum_runs: 5

      - name: Delete older versions
        uses: actions/delete-package-versions@v3
        with:
            package-name: 'com.sf.newroutes'
            min-versions-to-keep: 2
